fix capability for Composition #259
gematik/spec-ISiK-Basismodul pull request #260
Opened 2023-05-15 12:37 UTC by f-peverali

2023-05-15 20:01 UTC, alexzautke requested changes

2023-05-15 20:01 UTC, alexzautke commented on Resources/input/fsh/ISiKCapabilityStatement.fsh
> +* document.mode = #consumer
ISiKBerichtSubSysteme ist kein Document sondern eine Composition, document.mode kann hier nicht verwendet werden

2023-05-22 13:08 UTC, f-peverali commented on Resources/input/fsh/ISiKCapabilityStatement.fsh
> +* document.mode = #consumer
hier gelöst https://github.com/gematik/spec-ISiK-Basismodul/pull/260/commits/ffe2c9afd7d983ec1cd349ed854b21acb2069921

2023-05-28 09:22 UTC, alexzautke approved these changes

2023-05-28 09:22 UTC, merged