update links to R4 in IG
gematik/spec-ISiK-Basismodul pull request #296
Opened 2023-09-20 15:00 UTC by f-peverali

@MaxMTheilig bestenfalls lässt sich der Commit per cherry pick auf Stufe 2 anwenden?

2023-09-20 15:03 UTC, f-peverali commented
@MaxMTheilig Habe die Links manuell geprüft, da nicht alle per Search+Replace funktionierten. Wir sollten zukünftig aber mit Broken-Link-Checker prüfen... fällt dir einer ein, der für uns passen könnte?

2023-09-20 15:49 UTC, MaxMTheilig requested changes
Wir sollten alle Links, bei denen das möglich ist auf http**s**:// anstatt http:// ändern, wenn nichts dagegen spricht.

2023-09-21 14:50 UTC, f-peverali commented
@MaxMTheilig durch den letzten revert sollten die Interaktions-Beispiele in den IGs wieder einheitlich sein, wie besprochen.

2023-09-22 09:47 UTC, MaxMTheilig approved these changes

2023-09-22 09:57 UTC, merged