fix invariant context #330
gematik/spec-ISiK-Basismodul pull request #332
Opened 2023-11-17 12:20 UTC by f-peverali

## Pull Request Short Cut
bug fix for invariant - for explanation see links in bug ISSUE

2023-11-17 13:05 UTC, f-peverali commented
TODO:

- [ ] sobald positives review auch für Stufe 2 umzusetzen

2023-11-19 21:53 UTC, ylboerner requested changes
@f-peverali Super PR 👍 So hätte ich das Problem auch gelöst und Julian hat es ja auch so passend in den MII Profilen umgesetzt. 

Wir müssen noch ein paar Zeilen entfernen, dann gibt es ein Approval. Du kannst gerne eine Rereview direkt über Github anfragen und dann schaue ich nach den Änderungen noch einmal drüber.

2023-11-19 21:53 UTC, ylboerner commented on Resources/input/fsh/ISiKAngehoeriger.fsh
>      * ^constraint[1].source = Canonical(ISiKAngehoeriger)
`constraint.source` wird mittlerweile von SUSHI automatisch gesetzt und sollte noch entfernt werden.

```suggestion
```

2023-11-19 21:53 UTC, ylboerner commented on Resources/input/fsh/ISiKAngehoeriger.fsh
>      * ^constraint[1].source = Canonical(ISiKAngehoeriger)
`constraint.source` wird mittlerweile von SUSHI automatisch gesetzt und sollte noch entfernt werden.

```suggestion
```

2023-11-19 21:53 UTC, ylboerner commented on Resources/input/fsh/ISiKPatient.fsh
>      * ^constraint[1].source = Canonical(ISiKPatient)
`constraint.source` wird mittlerweile von SUSHI automatisch gesetzt und sollte noch entfernt werden.

```suggestion
```

2023-11-19 21:53 UTC, ylboerner commented on Resources/input/fsh/ISiKPatient.fsh
>      * ^constraint[1].source = Canonical(ISiKPatient)
`constraint.source` wird mittlerweile von SUSHI automatisch gesetzt und sollte noch entfernt werden.

```suggestion
```

2023-11-22 08:35 UTC, f-peverali commented
jetzt sollte es passen, @ylboerner Eigentlich hatte ich deine suggestions schon committed (s.o.)

2023-11-22 22:08 UTC, ylboerner approved these changes

2023-11-22 22:08 UTC, merged