Feature/anfisk 146 search related person
gematik/spec-ISiK-Basismodul pull request #346
Opened 2023-12-11 12:53 UTC by f-peverali

adds SearParameters

2024-01-03 22:28 UTC, alexzautke requested changes
Den Teil nach “ggf” kann ich nicht nachvollziehen

2024-01-03 22:29 UTC, alexzautke requested changes

2024-01-03 22:29 UTC, alexzautke commented on ImplementationGuide/markdown/DecisionLog.md
> +  * Option B (ggf. mit Nennung der Risiken): Keine Änderung - könnte ggf. zu Abweichung bei den oben gelisteten Abfragen führen
Mein Kommentar bezog sich hierauf. Sorry, hab mich in der GitHub UI verklickt.

2024-01-05 09:31 UTC, f-peverali commented on ImplementationGuide/markdown/DecisionLog.md
> +  * Option B (ggf. mit Nennung der Risiken): Keine Änderung - könnte ggf. zu Abweichung bei den oben gelisteten Abfragen führen
```suggestion
  * Option B (ggf. mit Nennung der Risiken): Keine Änderung. 
    * Risiko: könnte ggf. zu Abweichung bei den oben gelisteten Abfragen führen, bei Implementierung abweichender Custom-Suchparameter.
```

2024-01-05 09:32 UTC, alexzautke approved these changes

2024-01-05 09:32 UTC, merged