Fix/ptdata 825 coverage identifier
gematik/spec-ISiK-Basismodul pull request #362
Opened 2024-01-31 09:59 UTC by alexzautke

# Contributor Pull Request
Fixes PTDATA-825

## Description
Vorgaben für Coverage.identifier entfernt. Das Versicherungsverhältnis sollte per Chaining auf Patient ermittelt werden.

## Snippets or Screenshots (if necessary):

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-02-02 13:14 UTC, f-peverali requested changes
Sollten wir hier nicht von einem generischen "ISiKVersicherungsverhaeltnis" sprechen?

2024-02-02 13:14 UTC, f-peverali commented on ImplementationGuide/markdown/Versicherungsverhaeltnis/Versicherungsverhaeltnis_AnmerkungenZuDenMustSupportFeldern.md
Da wir auf die Aufhebung unterschiedlicher Coverage-Identifier-profile abzielen, sollte das auch hier schon Berücksichtigung finden. zumindest als informativer Satz?

2024-02-02 13:19 UTC, alexzautke commented on ImplementationGuide/markdown/Versicherungsverhaeltnis/Versicherungsverhaeltnis_AnmerkungenZuDenMustSupportFeldern.md
Das bezieht sich auf die Identifier im Patient. Zwei verschiedene Diskussionen.

2024-02-02 14:23 UTC, patrick-werner approved these changes

2024-02-02 14:51 UTC, f-peverali commented on ImplementationGuide/markdown/Versicherungsverhaeltnis/Versicherungsverhaeltnis_AnmerkungenZuDenMustSupportFeldern.md
Verstehe, ok.

2024-02-02 14:52 UTC, merged

2024-03-20 07:57 UTC, alexey-tschudnowsky commented on ImplementationGuide/markdown/Versicherungsverhaeltnis/Versicherungsverhaeltnis_AnmerkungenZuDenMustSupportFeldern.md
> +**Hinweise:** Grundsätzlich ist zu beachten, dass das Versicherungsverhältnis für die gesetzliche Versicherung durch die 30-stellige KVNR identifiziert wird. Die 10-stellige KVNR ist hingegen ein Ide
@f-peverali question: 10-stellige *KrankenversichertenID*? Die KVNR ist doch 30-stellig?

2024-03-20 08:11 UTC, alexzautke commented on ImplementationGuide/markdown/Versicherungsverhaeltnis/Versicherungsverhaeltnis_AnmerkungenZuDenMustSupportFeldern.md
> +**Hinweise:** Grundsätzlich ist zu beachten, dass das Versicherungsverhältnis für die gesetzliche Versicherung durch die 30-stellige KVNR identifiziert wird. Die 10-stellige KVNR ist hingegen ein Ide
Nur die ersten 10 Stellen sind für uns relevant, da nur dieser Teil unveränderlich ist.