Binaries müssen in ihrer nativen Form zurückgegeben werden
gematik/Spec-ISiK-Basismodul pull request #380
Opened 2024-03-10 21:58 UTC by alexzautke

#352 mit Rebase auf Stufe 4

2024-03-13 09:04 UTC, f-peverali requested changes
todo: bitte releasenote hinzu

2024-03-13 09:04 UTC, f-peverali commented on ImplementationGuide/markdown/Binary/Binary_Interaktionen.md
> +Um die Handhabung der base64-kodierten Binaries clientseitig zu erleichtern, MÜSSEN bei READ-Interaktionen Accept-Header mit einem Wert außer den [FHIR-Mime-Types](https://www.hl7.org/fhir/R4/http.ht
question: Fordern wir hier, dass ein Server einen beliebigen Accept-Header des clients (per content negotiation) unterstützen können muss? Klingt für mich erstmal fragwürdig... vielleicht aber nur ein Problem der Formulierung?

2024-03-13 09:21 UTC, alexzautke commented on ImplementationGuide/markdown/Binary/Binary_Interaktionen.md
> +Um die Handhabung der base64-kodierten Binaries clientseitig zu erleichtern, MÜSSEN bei READ-Interaktionen Accept-Header mit einem Wert außer den [FHIR-Mime-Types](https://www.hl7.org/fhir/R4/http.ht
Nein, der Trick hier ist, dass der Server erkennt, dass es sich nicht um einen FHIR-Mime-Type handelt. Anschließend entscheidet der Server welcher Binary-Mime-Type verwendet werden soll. Das kann abweichen vom Accept-Header!

2024-05-29 13:24 UTC, f-peverali approved these changes

2024-05-29 13:25 UTC, f-peverali reviewed
suggestion: bis zum weekly am 30. 5 nicht mergen

2024-05-30 12:43 UTC, f-peverali commented on ImplementationGuide/markdown/Binary/Binary_Interaktionen.md
> +Um die Handhabung der base64-kodierten Binaries clientseitig zu erleichtern, MÜSSEN bei READ-Interaktionen Accept-Header mit einem Wert außer den [FHIR-Mime-Types](https://www.hl7.org/fhir/R4/http.ht
```suggestion
Um die Handhabung der base64-kodierten Binary-Ressourcen clientseitig zu erleichtern, MUSS ein bestätigungsrelevantes System (Server) bei READ-Interaktionen Accept-Header mit einem Wert außer den [FHIR-Mime-Types](https://www.hl7.org/fhir/R4/http.html#mime-type) unterstützen. Falls ein solcher Accept-Header durch einen Client verwendet wird, MUSS  bestätigungsrelevante System (Server)  das Binary in seiner nativen Form (definiert durch Binary.contentType) zurückgeben.
```

2024-05-30 12:44 UTC, f-peverali approved these changes

2024-05-31 12:44 UTC, merged