Feature/add ms patient.link ptdata 676
gematik/Spec-ISiK-Basismodul pull request #384
Opened 2024-03-11 10:22 UTC by f-peverali

## Pull Request Short Cut

Solves https://github.com/gematik/spec-ISiK-Basismodul/issues/264#issuecomment-1553022809

and PTDATA-676

2024-03-11 11:11 UTC, alexzautke requested changes

2024-03-11 11:11 UTC, alexzautke commented on Resources/fsh-generated/resources/StructureDefinition-ISiKPatient.json
> +        "id": "Patient.link",
So wie ich @patrick-werner verstanden hatte ist es für die KIS-Systeme schwierig eine Instanz für die alten Patienten vorzuhalten. Besser wäre es hier nur die alte PID und Reference.identifier zu hinterlegen.

2024-03-11 15:07 UTC, f-peverali commented on Resources/fsh-generated/resources/StructureDefinition-ISiKPatient.json
> +        "id": "Patient.link",
question @patrick-werner : wie sollen wir hier mergen?

2024-03-17 08:08 UTC, patrick-werner commented
alle Inhalte nach #359 gemergt -> close

2024-03-17 08:08 UTC, closed without merging