ANFISK-241-Encounter.location
gematik/Spec-ISiK-Basismodul pull request #407
Opened 2024-05-27 12:15 UTC by jschoen-gefyra

added Encounter.location.status to slicing and MS
added status to example

Please go the the `Preview` tab and select the appropriate sub-template:

[**Contributor PR**](?expand=1&template=PR_Template_Contributor.md)

[Version Upgrade **(for Admins)**](?expand=1&template=PR_Template_VersionUpgrade.md)

## Pull Request Short Cut

2024-05-27 15:43 UTC, f-peverali requested changes
todo: Releasenotes einpflegen

suggestion (non-blocking) : ich würde die Entscheidung zu Dekumententationszwcken entsprechend in einem comment unter Encounter unterbringen. Sinngemäß: "Anhand der hier vorgegebenen Slices SOLL keine Historie der räumlichen Unterbringung vorgehalten werden."

2024-05-27 15:45 UTC, alexzautke commented
@f-peverali Meinst du "Anhand der hier vorgegebenen Slices ist es nicht verpflichtend eine Historie der räumlichen Unterbringung vorzuhalten."? Andernfalls klingt es so als würden wir davon abraten.

2024-05-28 11:31 UTC, f-peverali commented
> @f-peverali Meinst du "Anhand der hier vorgegebenen Slices ist es nicht verpflichtend eine Historie der räumlichen Unterbringung vorzuhalten."? Andernfalls klingt es so als würden wir davon abraten.
@alexzautke  - Durch die "vorgegebenen Slices", die in diesem PR alle #active im Status sind, kann keine Historie abgebildet werden, richtig? Damit wäre auch dieser Formulierungsvorschlag nicht optimal.
Vielleicht dann noch etwas hinzu, dass zur Nutzung eines anderen Slices rät, "falls die Abbildung einer Historie der räumlichen Unterbringung gewünscht ist" ?

2024-05-28 12:36 UTC, alexzautke commented
In jedem Slice gäbe es dass .period-Element, wir haben nur kein MS-Flag darauf definiert. Ein System könnte es aber eigenständig verwenden.

2024-05-29 13:29 UTC, f-peverali commented
> In jedem Slice gäbe es dass .period-Element, wir haben nur kein MS-Flag darauf definiert. Ein System könnte es aber eigenständig verwenden.

verstehe den hinweis nicht... in den Slice ist immer #active , was hilft da die period zur Abbildung? Wenn ein Slice #active ist, soll es ja gerade Abbildung der Ortshistorie unterstützten, oder?

2024-05-29 15:01 UTC, alexzautke commented
Ah, ich hatte nicht auf dem Schirm, dass wir status = active im Profil verlanden. Slicing auf PhysicalType und Status hätte doch auch gereicht? Passt. Weiterhin belieb ich dabei, dass wir sagen sollten, dass es nicht notwendig ist die Historie vorzuhalten. Ein Hersteller könnte weiterhin einen anderen Status freiwillig implementieren. Wir würden ja nicht davon abraten.

2024-05-30 12:34 UTC, f-peverali commented on Resources/fsh-generated/resources/StructureDefinition-ISiKKontaktGesundheitseinrichtung.json
> +        "id": "Encounter.location:Station.status",
issue: pattern muss auf location , nicht wie hier auf status

2024-05-30 14:46 UTC, patrick-werner approved these changes

2024-06-07 10:10 UTC, merged