add VS for compatibility with Terminplanung - Stufe 4
gematik/Spec-ISiK-Basismodul pull request #418
Opened 2024-06-13 15:10 UTC by f-peverali

# Contributor Pull Request

## Description
Solves ANFISK 275 and 272 by adding ValueSets 
Creates a more coherent coding accoss ISIk modules regarding organizational units

## Motivation and Context

## How has this been tested?

## Snippets or Screenshots (if necessary):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this IG / specification.
- [ ] My change requires a change to the documentation or narrative (intend) of the IG.
- [x] I have already updated the documentation / narrative (intend) accordingly.
- [x] ReleaseNotes for feature/fix are updated in releaseNotes.md

2024-06-21 09:20 UTC, f-peverali commented on Resources/input/fsh/ISiKOrganisation.fsh
> +  * ^comment = "Motivation: Ein System muss den Namen einer Organisation zum Abruf bereitstellen, sofern diese Information verfügbar ist.."
```suggestion
  * ^comment = "Motivation: Ein System muss den Namen einer Organisation zum Abruf bereitstellen, sofern diese Information verfügbar ist."

```

2024-06-23 20:52 UTC, alexzautke requested changes
Eine Anmerkung zu der Änderung bzgl. ANFSIK-275. Generell ist der PR ein wenig unsauber, da andere Änderungen noch zeitgleich eingebracht werden. Ich würde vorschlagen, dass in zwei separaten PRs zu machen.

2024-06-23 20:52 UTC, alexzautke commented on Resources/input/fsh/ISiKOrganisation.fsh
> +* type[Fachrichtung] from $organization_type (required)
Falsches VS hier, anstatt $organization_type sollte hier der PracticeSettingCode verwendet werden

2024-06-24 07:19 UTC, f-peverali commented on Resources/input/fsh/ISiKOrganisation.fsh
> +* type[Fachrichtung] from $organization_type (required)
@alexzautke , wir sollten hier ggf. noch das faclityTypeCode VS (https://wiki.hl7.de/index.php?title=Ihevs:DocumentEntry.healthcareFacilityTypeCode) für die Codierung der Einrichtungsart heranziehen?

2024-06-24 07:23 UTC, alexzautke approved these changes

2024-06-24 07:24 UTC, alexzautke commented on Resources/input/fsh/ISiKOrganisation.fsh
> +* type[Fachrichtung] from $organization_type (required)
Ja, das ist eine gute Idee

2024-06-24 14:16 UTC, f-peverali commented on Resources/input/fsh/ISiKOrganisation.fsh
> +* type[Fachrichtung] from $organization_type (required)
done

2024-06-24 14:30 UTC, alexzautke commented on Resources/input/fsh/ISiKOrganisation.fsh
> +* type[Fachrichtung] from $organization_type (required)
Ich kann den Slice nicht sehen

2024-06-25 09:25 UTC, alexzautke commented on Resources/fsh-generated/resources/StructureDefinition-ISiKOrganisationFachabteilung.json
> +        "id": "Organization.type:Fachbereich",
IHE spricht beim PracticeSettingCode von "Fachgebieten" wollen wir das übernehmen?

2024-06-25 09:37 UTC, f-peverali commented on Resources/fsh-generated/resources/StructureDefinition-ISiKOrganisationFachabteilung.json
> +        "id": "Organization.type:Fachbereich",
suggestion: An sich finde ich den Hinweis gut. Wording im Slice ist als Änderung aber "non-blocking" ... ich würde da nochmal die Stakeholder hören und das ggf. gemeinsam mit dem Modul Terminplanung anpassen. Diesen PR merge ich so.

2024-06-25 09:38 UTC, merged