PTDATA-1070 remove MS for .id
gematik/Spec-ISiK-Basismodul pull request #468
Opened 2024-10-18 12:13 UTC by jschoen-gefyra

# Contributor Pull Request

## Description
Remove MS for id

## Motivation and Context
Solves [PTDATA-1070](https://service.gematik.de/browse/PTDATA-1070)

## How has this been tested?
-

## Snippets or Screenshots (if necessary):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this IG / specification.
- [ ] ReleaseNotes for feature/fix are updated in releaseNotes.md

2024-10-19 18:25 UTC, alexzautke submitted a review, later dismissed

2024-10-19 18:26 UTC, alexzautke requested changes
Der PR sollte gegen einen TC-Branch gehen oder?

2024-10-21 07:14 UTC, f-peverali approved these changes

2024-10-21 07:15 UTC, f-peverali commented
suggestioN. @jschoen-gefyra @alexzautke TC_3.0.6  ist der richtige Target Branch

2024-10-25 11:49 UTC, jschoen-gefyra commented
@f-peverali konnte es switchen und es scheint nur das zu betreffen, was neu ist. Ich habe noch den Changelog erweitert.

2024-10-25 12:37 UTC, merged